# Generated by Django 4.0.2 on 2022-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Halalan2022', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(auto_now_add=True),
        ),
    ]
