# Generated by Django 4.0.2 on 2022-05-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Halalan2022', '0009_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
