# Generated by Django 4.0.2 on 2022-05-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Halalan2022', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
