# Generated by Django 4.0.2 on 2022-05-16 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Halalan2022', '0018_alter_candidate_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Halalan2022.userperson'),
        ),
    ]
