# Generated by Django 4.0.2 on 2022-05-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Halalan2022', '0019_alter_vote_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='slogan',
            field=models.CharField(max_length=500),
        ),
    ]
