# Generated by Django 4.0.2 on 2022-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Halalan2022', '0023_alter_vote_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperson',
            name='conditional',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
