# Generated by Django 4.0.2 on 2022-05-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Halalan2022', '0024_userperson_conditional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperson',
            name='conditional',
        ),
    ]
