# Generated by Django 4.2 on 2023-04-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('itemid', models.IntegerField(primary_key=True, serialize=False, verbose_name=200)),
                ('price', models.IntegerField(verbose_name=5)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
