# Generated by Django 4.2 on 2023-04-21 13:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0005_alter_item_itemid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='Gael Estrera', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=241, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='outofstock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
