# Generated by Django 4.2 on 2023-04-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0006_alter_item_managers_remove_item_itemid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
