# Generated by Django 4.2 on 2023-04-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountpaid', models.IntegerField(default=0)),
                ('orderdate', models.DateField(auto_now_add=True)),
                ('paymenttype', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='item_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_total', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A1.item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A1.order')),
            ],
        ),
    ]
