# Generated by Django 4.2 on 2023-04-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0010_alter_item_order_managers_alter_order_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock',
            new_name='stock_quantity',
        ),
    ]
