# Generated by Django 4.0.2 on 2022-03-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myinventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='Createdat',
            new_name='CreatedAt',
        ),
    ]
