# Generated by Django 4.0.2 on 2022-12-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_orderedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Stock',
            field=models.BigIntegerField(default=10),
            preserve_default=False,
        ),
    ]
