# Generated by Django 4.0.2 on 2022-12-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='totalcost',
            field=models.IntegerField(default=0),
        ),
    ]
